# Generated by Django 5.1.3 on 2024-12-01 20:29

import apps.authentication.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region=None, serialize=False, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=4, null=True)),
                ('code_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invite_code', models.CharField(default=apps.authentication.models.generate_unique_invite_code, max_length=6)),
                ('activated_code', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
